### ISSUE TITLE
client.c

### ISSUE THREAD

**Issue by ggml1** [luucasv/projetoIP#1]
Uma das coisas que eu tive problema quando tava estruturando o jogo, foi no fato de que quando a conexão não era aceita, o servidor simplesmente dava exit(1) e crashava. Aí eu pensei que isso poderia ficar mias intuitivo, e aí, no client.c, ao invés das funções darem exit(1), elas poderiam ter um retorno, a ser interpretado pela main pra mostrar uma mensagem de erro ou algo pro usuário, aí assim ele vai ter como saber qual foi o problema, ao invés de só levar um crash e ficar perdido..

https://github.com/ggml1/projetoip/blob/master/libSocket/client.c <- meu client.c

Dividi a parte do connect to server em três tipos de retorno:

-2, caso não seja possível criar o socket
-1, caso a conexão não seja bem sucedida (ip não existe, server off, etc)
0, caso o servidor esteja full

E adicionei outra função, caso o jogo já tenha começado, pra que o usuário não entre no meio da partida
(retorno -3). pra isso, mudei o server_response, que recebe um valor da função acceptConnection, que tá no server.c, dessa forma:

(mais detalhes: https://github.com/ggml1/projetoip/blob/master/libSocket/server.c)

```
> if(clients_connected == actual_max_clients){ // there are too many clients connected
> 		return_msg = TOO_MANY_CLIENTS;
> 		write(new_sock, &return_msg, sizeof(int));
> 		close(new_sock);
> 	}
> 	**else if(naoComeca == 0){
> 		return_msg = GAME_ALREADY_STARTED;
> 		write(new_sock, &return_msg, sizeof(int));
> 		close(new_sock);
> 	}**
> 	else{
> 		++clients_connected;
> 		int i;
> 		return_msg = SUCCESSFUL_CONNECTION;
> 		for(i = 0; i < actual_max_clients; ++i){ // look for available space for this new client
> 			if(connected_clients[i].sockid == 0){
> 				write(new_sock, &return_msg, sizeof(int));
> 				FD_SET(new_sock, &active_fd_set);
> 				connected_clients[i].sockid = new_sock;
> 				return i;
> 			}
> 		}
> 	}
```

A função acceptConnection recebe uma variável naoComeca como parametro, e aí, se ela for 0, significa que o game já começou, e o retorno da função passa a ser o GAME_ALREADY_STARTED

por enquanto, acho que é só isso, se quiser ver mais em detalhes, tá na lib do meu client, deixei os links certinhos aí!

xero

**Comment by luucasv** [comment]
Issue resolvida. 
Agora a função "connectToServer" retorna um enum que identifica cada possível status do servidor.
Já o segundo problema foi resolvido da seguinte forma: caso em algum momento o servidor esteja indisponível para receber novas conexões, as chamadas a função "acceptConnection" devem ser trocadas por "rejectConnection" (esta resulta no resultado SERVER_CLOSED ao cliente tentar se conectar ao servidor).
Uma melhor documentação destas funcionalidades serão adicionadas às antigas documentações.
