### ISSUE TITLE
Opcao de desconectar o cliente.

### ISSUE THREAD

**Issue by Jobesco** [luucasv/projetoIP#3]
Sugiro que voces incluam uma funcao em client.c que desconecte ele do server,e que ele nao dependa somente de connectToServer,pois assim,ele é impossibilitado de se conectar a qualquer outro server enquanto o codigo nao for recompilado.

A maneira que usei pra testar isso foi a seguinte:
o server inicializa,executa um loop,depois dá server reset,enquanto no client,ele é desconectado pelo server,mas quando uso a funcao connectToServer novamente,ele nao funciona,somente quando eu recompilo,que ele consegue se reconectar com sucesso ao server(cujo nao foi recompilado,apenas executou um server reset

**Comment by luucasv** [comment]
Olá jubesco. Obrigado por mostrar está falha no sistema. Já sei do que se trata e tentarei o mais rápido possível resolver.
Em breve voltarei com as modificações desejadas.

**Comment by luucasv** [comment]
Desculpa pela demora, mas, ao que parece, este problema não acontece. Para mais informações, rodar o teste "serverResetTest" adicionado a pasta "tests".
Então, por conta disso, estou fechando esta issue.
